# -*- coding: utf-8 -*-
"""nested control structure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQNtZDv6MGBDiE9lm2YHixu7ocp3DqTD
"""

age = 20
marks = 70

if age >= 18:
    if marks >= 60:
        print("داخلہ ہو گیا")
    else:
        print("نمبر کم ہیں")
else:
    print("عمر کم ہے")

for i in range(1, 4):
    for j in range(1, 3):
        print(i, j)